### PR TITLE
mice.1chain() adaptation for mice 3.0

### PR DESCRIPTION
**Pull request by stefvanbuuren**
The arguments of the `mice::mice` function will change with version 3.0 of `mice`. See https://github.com/stefvanbuuren/mice/blob/dev/vignettes/changes_mice3.md

This pull request is a suggestion for how to adapt the call to `mice::mice` to the new definition. I believe it works as expected, but please check carefully. The imputes look reasonable, but further down the line there's an error in the plotting routine. Also, documentation still needs updating. 

Nevertheless, I hope it could be useful.

### CODE REVIEW

**Comment by stefvanbuuren** [comment]
Alexander, yes, I got rid of the mids$p component, which I never quite liked as it duplicated lots of stuff.
I hope your adaptations will be straightforward. I’d be happy to answer any queries you might have.
Stef.

Van: Alexander Robitzsch <notifications@github.com>
Beantwoorden - Aan: alexanderrobitzsch/miceadds <reply@reply.github.com>
Datum: maandag 28 mei 2018 om 09:25
Aan: alexanderrobitzsch/miceadds <miceadds@noreply.github.com>
CC: "S. Buuren" <S.vanBuuren@uu.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [alexanderrobitzsch/miceadds] mice.1chain() adaptation for mice 3.0 (#8)


I included the suggested changes. It seems that you rewrote the sampler function and you renamed objects (e.g., vname to yname; I cannot find object "p", ...) . These changes broke several functions in miceadds, but I hope that I can fix it in the next days.

**Comment by alexanderrobitzsch** [comment]
Adaptations have been made in `miceadds 2.12-15`.

**Comment by alexanderrobitzsch** [comment]
Hi Stef,

Maybe this is more of a comment than a bug, but I just want to let you know about consequences of a change in `mice.impute.norm`. I checked some of my examples and found that some of the imputation functions in `miceadds` which call other imputation functions do not work anymore (e.g.,  `mice.impute.2lonly.function`, `mice.impute.plausible.values`). The problem seems to appear with `mice.impute.norm`. In the recent function version, some object `state` is searched in a parent environment. I guess that the problem is due to `estimice` which uses function `updateLog` which has a direct link to a parent frame of fixed order (e.g., `parent.frame(n=4)`). This works if the level at which the imputation function is applied does not change. However, in my example, `parent.frame(n=5)` has to be applied because the `mice` imputation method is used as a subfunction. I could circuumvent the problem by submitting the argument `ls.meth="ridge"` which is itself an argument for `estimice`. It seems that `ls.meth="ridge"` avoids access to some fixed `perent.frame`.

Any hints about this issue?
Alexander

**Comment by stefvanbuuren** [comment]
Probably the quick solution would be to add an extra argument to `estimice` that allows changing the hard-coded frame number. 

More generally, `updateLog` is very easy to break since its success depends where it is called. Alternatively, I could create a separate environment at initialization for writing messages. I guess that will be more robust. Do you know of any packages that use such a scheme that I can learn from?

**Comment by alexanderrobitzsch** [comment]
> Probably the quick solution would be to add an extra argument to estimice that allows changing the hard-coded frame number.

This would be a good solution, I think.

> More generally, updateLog is very easy to break since its success depends where it is called. Alternatively, I could create a separate environment at initialization for writing messages. I guess that will be more robust. Do you know of any packages that use such a scheme that I can learn from?

I do not know any packages, but very probably there are examples for it. I made a quick hack for searching objects within environments for my imputation functions:

[https://github.com/alexanderrobitzsch/miceadds/blob/master/R/ma_exists.R](url)

I search for object `x` in parent environments. It is not unique, but I guess that in many cases it is sufficient.

**Comment by stefvanbuuren** [comment]
I just pushed `mice 3.0.4`, which uses your `ma_exists()` function to find the proper environment for `state` and `loggedEvents`. Does this work for you?

I have copied your function so as to evade mutual dependencies, and added a note to your original.

**Comment by alexanderrobitzsch** [comment]
That is good. I think that now I am quite satistified.

**Pull request closed without merging**
